# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hackathon_development

test:
  <<: *default
  database: hackathon_test
production:
  <<: *default
  database: hackathon_production
  username: hackathon
  password: <%= ENV['HACKATHON_DATABASE_PASSWORD'] %>
